//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DynamicsGPEntities : DbContext
    {
        public DynamicsGPEntities()
            : base("name=DynamicsGPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwRmClientes> vwRmClientes { get; set; }
    
        [DbFunction("DynamicsGPEntities", "comgp_fnDocStatusPreCondiciones")]
        public virtual IQueryable<comgp_fnDocStatusPreCondiciones_Result> comgp_fnDocStatusPreCondiciones(Nullable<short> tIPODOCGP, string nUMDOCGP, string tRANSICION)
        {
            var tIPODOCGPParameter = tIPODOCGP.HasValue ?
                new ObjectParameter("TIPODOCGP", tIPODOCGP) :
                new ObjectParameter("TIPODOCGP", typeof(short));
    
            var nUMDOCGPParameter = nUMDOCGP != null ?
                new ObjectParameter("NUMDOCGP", nUMDOCGP) :
                new ObjectParameter("NUMDOCGP", typeof(string));
    
            var tRANSICIONParameter = tRANSICION != null ?
                new ObjectParameter("TRANSICION", tRANSICION) :
                new ObjectParameter("TRANSICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<comgp_fnDocStatusPreCondiciones_Result>("[DynamicsGPEntities].[comgp_fnDocStatusPreCondiciones](@TIPODOCGP, @NUMDOCGP, @TRANSICION)", tIPODOCGPParameter, nUMDOCGPParameter, tRANSICIONParameter);
        }
    }
}
