//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class INTEGRAEntities : DbContext
    {
        public INTEGRAEntities()
            : base("name=INTEGRAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwIntegracionesVentas> vwIntegracionesVentas { get; set; }
        public virtual DbSet<vwPreFacturas> vwPreFacturas { get; set; }
    
        [DbFunction("INTEGRAEntities", "docGetSiguienteStatus")]
        public virtual IQueryable<docGetSiguienteStatus_Result> docGetSiguienteStatus(Nullable<short> tIPODOCARN, string nUMDOCARN, string tRANSICION)
        {
            var tIPODOCARNParameter = tIPODOCARN.HasValue ?
                new ObjectParameter("TIPODOCARN", tIPODOCARN) :
                new ObjectParameter("TIPODOCARN", typeof(short));
    
            var nUMDOCARNParameter = nUMDOCARN != null ?
                new ObjectParameter("NUMDOCARN", nUMDOCARN) :
                new ObjectParameter("NUMDOCARN", typeof(string));
    
            var tRANSICIONParameter = tRANSICION != null ?
                new ObjectParameter("TRANSICION", tRANSICION) :
                new ObjectParameter("TRANSICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<docGetSiguienteStatus_Result>("[INTEGRAEntities].[docGetSiguienteStatus](@TIPODOCARN, @NUMDOCARN, @TRANSICION)", tIPODOCARNParameter, nUMDOCARNParameter, tRANSICIONParameter);
        }
    
        public virtual int sp_LOGINTEGRACIONESInsert(ObjectParameter iD, Nullable<short> tIPODOCARN, string nUMDOCARN, Nullable<short> tIPODOCGP, string nUMDOCGP, string tRANSICION, string uSUARIO, string mENSAJE, string mSJPRECONDICIONES, Nullable<short> cUMPLEPRECONDICIONES)
        {
            var tIPODOCARNParameter = tIPODOCARN.HasValue ?
                new ObjectParameter("TIPODOCARN", tIPODOCARN) :
                new ObjectParameter("TIPODOCARN", typeof(short));
    
            var nUMDOCARNParameter = nUMDOCARN != null ?
                new ObjectParameter("NUMDOCARN", nUMDOCARN) :
                new ObjectParameter("NUMDOCARN", typeof(string));
    
            var tIPODOCGPParameter = tIPODOCGP.HasValue ?
                new ObjectParameter("TIPODOCGP", tIPODOCGP) :
                new ObjectParameter("TIPODOCGP", typeof(short));
    
            var nUMDOCGPParameter = nUMDOCGP != null ?
                new ObjectParameter("NUMDOCGP", nUMDOCGP) :
                new ObjectParameter("NUMDOCGP", typeof(string));
    
            var tRANSICIONParameter = tRANSICION != null ?
                new ObjectParameter("TRANSICION", tRANSICION) :
                new ObjectParameter("TRANSICION", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var mENSAJEParameter = mENSAJE != null ?
                new ObjectParameter("MENSAJE", mENSAJE) :
                new ObjectParameter("MENSAJE", typeof(string));
    
            var mSJPRECONDICIONESParameter = mSJPRECONDICIONES != null ?
                new ObjectParameter("MSJPRECONDICIONES", mSJPRECONDICIONES) :
                new ObjectParameter("MSJPRECONDICIONES", typeof(string));
    
            var cUMPLEPRECONDICIONESParameter = cUMPLEPRECONDICIONES.HasValue ?
                new ObjectParameter("CUMPLEPRECONDICIONES", cUMPLEPRECONDICIONES) :
                new ObjectParameter("CUMPLEPRECONDICIONES", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LOGINTEGRACIONESInsert", iD, tIPODOCARNParameter, nUMDOCARNParameter, tIPODOCGPParameter, nUMDOCGPParameter, tRANSICIONParameter, uSUARIOParameter, mENSAJEParameter, mSJPRECONDICIONESParameter, cUMPLEPRECONDICIONESParameter);
        }
    }
}
