//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPreFacturas
    {
        public short TIPODOC { get; set; }
        public string NUMERODOC { get; set; }
        public string IDCLIENTE { get; set; }
        public System.DateTime FECHADOC { get; set; }
        public string OBSERVACIONES { get; set; }
        public int NUMLINEA { get; set; }
        public string IDITEM { get; set; }
        public string DESCRIPCION { get; set; }
        public string UDM { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
    }
}
