DROP TABLE compuertagp.PREFACTURADET;

DROP TABLE compuertagp.LOGINTEGRACIONES;

DROP TABLE compuertagp.PREFACTURACAB;


CREATE TABLE compuertagp.PREFACTURACAB (
  TIPODOC SMALLINT  NOT NULL  ,
  NUMERODOC VARCHAR(20)  NOT NULL  ,
  IDCLIENTE VARCHAR(15)  NOT NULL  ,
  FECHADOC DATETIME  NOT NULL  ,
  OBSERVACIONES VARCHAR(30)  NOT NULL    ,
  DOCID_GP VARCHAR(15) null,
  SOPTYPE_GP SMALLINT null
PRIMARY KEY(TIPODOC, NUMERODOC));
GO

--alter table compuertagp.PREFACTURACAB add SOPTYPE_GP SMALLINT null


CREATE TABLE compuertagp.PREFACTURADET (
  NUMLINEA INTEGER  NOT NULL   IDENTITY ,
  PREFACTURACAB_NUMERODOC VARCHAR(20)  NOT NULL  ,
  PREFACTURACAB_TIPODOC SMALLINT  NOT NULL  ,
  IDITEM VARCHAR(30)  NOT NULL  ,
  DESCRIPCION VARCHAR(100)  NOT NULL  ,
  UDM VARCHAR(9)  NOT NULL  ,
  CANTIDAD NUMERIC(19,5)  NOT NULL  ,
  PRECIO NUMERIC(19,5)  NOT NULL    ,
PRIMARY KEY(NUMLINEA, PREFACTURACAB_NUMERODOC, PREFACTURACAB_TIPODOC)  ,
  FOREIGN KEY(PREFACTURACAB_TIPODOC, PREFACTURACAB_NUMERODOC)
    REFERENCES compuertagp.PREFACTURACAB(TIPODOC, NUMERODOC)
      ON DELETE CASCADE);
GO

CREATE TABLE compuertagp.LOGINTEGRACIONES (
  ID INTEGER  NOT NULL   IDENTITY ,
  TIPODOCARN SMALLINT  NOT NULL  ,
  NUMDOCARN VARCHAR(20)  NOT NULL  ,
  TIPODOCGP SMALLINT    ,
  NUMDOCGP VARCHAR(20)    ,
  DOCSTATUS VARCHAR(20)  NOT NULL  ,
  ESACTUAL SMALLINT  NOT NULL  ,
  USUARIO VARCHAR(35)  NOT NULL  ,
  FECHAHORA DATETIME  NOT NULL  ,
  MENSAJE VARCHAR(150)  NOT NULL  ,
  MENSAJELARGO VARCHAR(MAX)      ,
PRIMARY KEY(ID));
GO

create index LOGINTEGRACIONES_Idx1 on compuertagp.LOGINTEGRACIONES (TIPODOCARN, NUMDOCARN, ESACTUAL) INCLUDE(ID, DOCSTATUS, NUMDOCGP, TIPODOCGP, USUARIO, FECHAHORA,  MENSAJE ,  MENSAJELARGO);
create index LOGINTEGRACIONES_Idx2 on compuertagp.LOGINTEGRACIONES (NUMDOCGP, TIPODOCGP, ESACTUAL) INCLUDE(ID, DOCSTATUS, TIPODOCARN, NUMDOCARN, USUARIO, FECHAHORA,  MENSAJE ,  MENSAJELARGO);
go


CREATE INDEX PREFACTURAD_FKIndex1 ON compuertagp.PREFACTURADET (PREFACTURACAB_TIPODOC, PREFACTURACAB_NUMERODOC);
GO


CREATE INDEX IFK_Rel_01 ON compuertagp.PREFACTURADET (PREFACTURACAB_TIPODOC, PREFACTURACAB_NUMERODOC);
GO


